### ISSUE TITLE
[help] 启动后没有install选项

### ISSUE THREAD

**Issue by dingxiaobo** [optiplex-osx/Dell-OptiPlex-7040-Clover-EFI#10]
## 启动后没有install选项 我的步骤是这样的：

1. 在mac上 下载了最新的Mojave镜像，用`createinstallmedia`制作了启动u盘

1. 在mac上 下载了5018版本的clover，安装clover到启动u盘的 EFI分区

1. 删除EFI分区里的EFI目录，放入您提供的EFI

1. 到7040上关闭secureboot后使用u盘启动

1. 看到了如下界面
![微信图片_20190731121833](https://user-images.githubusercontent.com/23743074/62183727-e24d7b00-b38d-11e9-936f-9c6454677218.jpg)

1. 接下来执行uefi shell命令，执行完后退出uefishell
![微信图片_20190731121841](https://user-images.githubusercontent.com/23743074/62183769-07da8480-b38e-11e9-942a-f2d41ec68430.jpg)

1. clover界面和上图还是一致，我又按了`F3`，多出了`Boot UEFI internal from EFI`，这个选项启动还是原来的windows系统
![243143128950388253](https://user-images.githubusercontent.com/23743074/62183808-280a4380-b38e-11e9-8811-bd780e1fa1d3.jpg)

### 这是我的设备信息
![微信图片_20190731121815](https://user-images.githubusercontent.com/23743074/62183853-5720b500-b38e-11e9-9dac-6e624b018218.jpg)
![389650963672274027](https://user-images.githubusercontent.com/23743074/62183857-5a1ba580-b38e-11e9-8db2-cca8120050d7.jpg)
![296709967812568622](https://user-images.githubusercontent.com/23743074/62183860-5be56900-b38e-11e9-8ff6-4be1b153a266.jpg)

**Comment by dingxiaobo** [comment]
求助，我是哪一步错了什么？
该怎样出现install选项？

**Comment by dingxiaobo** [comment]
再尝试用etcher写了一遍u盘

把本项目内容复制到 EFI分区

现象仍然一致。。。 懵了


etcher写了之后的u盘结构
![深度截图_选择区域_20190731130645](https://user-images.githubusercontent.com/23743074/62185250-44a97a00-b394-11e9-8975-7db7f32c45da.png)

**Comment by irelandKen** [comment]
估计`install选项`显示这一块真的有BUG

你可以直接用[小兵](https://blog.daliansky.net/macOS-Mojave-10.14.6-18G84-Release-version-with-Clover-5027-original-image.html)的EFI先安装, 等安装成功后再切回这个EFI来启动就好

**Comment by dingxiaobo** [comment]
> 估计`install选项`显示这一块真的有BUG
> 
> 你可以直接用[小兵](https://blog.daliansky.net/macOS-Mojave-10.14.6-18G84-Release-version-with-Clover-5027-original-image.html)的EFI先安装, 等安装成功后再切回这个EFI来启动就好

还真是有bug，看了下`EFI/CLOVER/drivers64UEFI`里没有`HFSPlus.efi`。

usb介质是HFS的filesystem，放进`HFSPlus.efi`之后，可以看到安装选项
![332072103397737712](https://user-images.githubusercontent.com/23743074/62188063-d8cc0f00-b39d-11e9-923b-eefd694043f5.jpg)

**Comment by dingxiaobo** [comment]
进度反馈，现在滚完进度条后显示器无信号。

等空的时候再研究，如果能装成功，我到时候提交个pr。

干活去了。。。

**Comment by irelandKen** [comment]
> 进度反馈，现在滚完进度条后显示器无信号。
> 
> 等空的时候再研究，如果能装成功，我到时候提交个pr。
> 
> 干活去了。。。

`显示器无信号`, 需要切换到另一个DP口

**Comment by dingxiaobo** [comment]
补了`HFSPlus.efi`、换了dp接口之后    

撒花

# 成功啦  
![446334945237597941](https://user-images.githubusercontent.com/23743074/62195056-ba6e0f80-b3ad-11e9-9a04-6761b384a4fb.jpg)

**Comment by irelandKen** [comment]
GOOD, 倍儿棒~

**Comment by wenjiahui** [comment]
谢谢两个大佬，终于安装成功了。 安装过程也遇到滚完进度条后显示器无信号的情况，换dp接口可以解决。 但是安装界面界面识别不了本地的磁盘，需要将黑果小兵的中SATA—xxx.kext驱动放到clover/kexts/other目录下才行。  不过进入系统后发现了一个新的问题，就是如果关闭显示屏后，再次打开，会一直提示进入省电模式，唤醒不了。 请问这是什么原因导致的？

**Comment by irelandKen** [comment]
> 谢谢两个大佬，终于安装成功了。 安装过程也遇到滚完进度条后显示器无信号的情况，换dp接口可以解决。 但是安装界面界面识别不了本地的磁盘，需要将黑果小兵的中SATA—xxx.kext驱动放到clover/kexts/other目录下才行。 不过进入系统后发现了一个新的问题，就是如果关闭显示屏后，再次打开，会一直提示进入省电模式，唤醒不了。 请问这是什么原因导致的？

关闭显示器之后无法唤醒的问题我也遇到过, 现在一直不关显示器使用...

**Comment by wenjiahui** [comment]
> > 谢谢两个大佬，终于安装成功了。 安装过程也遇到滚完进度条后显示器无信号的情况，换dp接口可以解决。 但是安装界面界面识别不了本地的磁盘，需要将黑果小兵的中SATA—xxx.kext驱动放到clover/kexts/other目录下才行。 不过进入系统后发现了一个新的问题，就是如果关闭显示屏后，再次打开，会一直提示进入省电模式，唤醒不了。 请问这是什么原因导致的？
> 
> 关闭显示器之后无法唤醒的问题我也遇到过, 现在一直不关显示器使用...

刚刚中午升级系统到最新版10.14.6， 没想到就正常了。目前唤醒没问题。

**Comment by irelandKen** [comment]
666

**Comment by dingxiaobo** [comment]
> > > 谢谢两个大佬，终于安装成功了。 安装过程也遇到滚完进度条后显示器无信号的情况，换dp接口可以解决。 但是安装界面界面识别不了本地的磁盘，需要将黑果小兵的中SATA—xxx.kext驱动放到clover/kexts/other目录下才行。 不过进入系统后发现了一个新的问题，就是如果关闭显示屏后，再次打开，会一直提示进入省电模式，唤醒不了。 请问这是什么原因导致的？
> > 
> > 
> > 关闭显示器之后无法唤醒的问题我也遇到过, 现在一直不关显示器使用...
> 
> 刚刚中午升级系统到最新版10.14.6， 没想到就正常了。目前唤醒没问题。

666   我也是一直不关显示器用，现在更新了10.14.6 。好了，放心关显示器☺️
