### ISSUE TITLE
插AMD独显

### ISSUE THREAD

**Issue by jinxiangqiang** [optiplex-osx/Dell-OptiPlex-7040-Clover-EFI#3]
大神，我是同款机型，我想插在独显上的时候核显也被驱动，但是bios里似乎自动屏蔽了，我怎么开启

**Comment by irelandKen** [comment]
我现在换机器啦, 我用的MSI八代主板,  插上独显后, 核显确实默认被屏蔽的, 然后在BIOS里启用就好. 

是说你的情况和上述类似, 但BIOS里没相关选择来开启?

**Comment by irelandKen** [comment]
在BIOS里启用核显即可
