### ISSUE TITLE
macOS 10.14.5 test

### ISSUE THREAD

**Issue by irelandKen** [optiplex-osx/Dell-OptiPlex-7040-Clover-EFI#6]
I need some volunteer to test macOS 10.14.4 for me, just because the OptiPlex 7040 machine is not on my hand now.

Help wanted, just email to me.

see [beta release](https://github.com/irelandKen/OptiPlex-7040-Clover/releases/tag/v4.0-beta2)

**Comment by ONEokDAMON** [comment]
Hi
I'm 100% want to do a volunteer on my 7040 Optiplex machine. Please kindly help. My QQ: 740756835
if you need some other contact, I will leave aside.

**Comment by irelandKen** [comment]
> Hi
> I'm 100% want to do a volunteer on my 7040 Optiplex machine. Please kindly help. My QQ: 740756835
> if you need some other contact, I will leave aside.

Yeah, you are welcome. 

I've already sent you a friend invite on QQ, please go check.

**Comment by ilaysener** [comment]
I have 7040 and 7050 micro, both with i5 6600T CPUs. More than happy to test as well. I am running 14.14.4

**Comment by irelandKen** [comment]
> I have 7040 and 7050 micro, both with i5 6600T CPUs. More than happy to test as well. I am running 14.14.4
> 
> Can send email to [dsener@yahoo.com](mailto:dsener@yahoo.com)

Yeah, you are welcome.

**Comment by yeZLTaeyeon** [comment]
你好，我的也是OptiPlex 7040  i7处理器，我现在要装个黑苹果10.14.4，之前是按照https://blog.csdn.net/qq_24671941/article/details/82901391 这篇文章实验的，可惜卡在了安装系统-按F12一直没有出现我的U盘，现在找到了这里，想请教大神指定一下，我是个小白，qq:  2544627835 ,非常期待你的到来，万分感谢~

**Comment by irelandKen** [comment]
你好，安装流程你可以参考https://blog.daliansky.net/MacOS-installation-tutorial-XiaoMi-Pro-installation-process-records.html，并结合本仓库的README来试试。

**Comment by irelandKen** [comment]
> 你好，我的也是OptiPlex 7040 i7处理器，我现在要装个黑苹果10.14.4，之前是按照https://blog.csdn.net/qq_24671941/article/details/82901391 这篇文章实验的，可惜卡在了安装系统-按F12一直没有出现我的U盘，现在找到了这里，想请教大神指定一下，我是个小白，qq: 2544627835 ,非常期待你的到来，万分感谢~

Hi, 安装步骤请参考"https://blog.daliansky.net/MacOS-installation-tutorial-XiaoMi-Pro-installation-process-records.html", 安装U盘制作完成后用本EFI替换即可.

**Comment by Rand01ph** [comment]
你好，我刚给新配置的主机安装了10.14.5，想使用你的配置文件给OptiPlex 7040 i7安装10.14.5，我看到有个Know issue说只有一个DP口生效，但是我现在使用了两个DP口转接VGA的双显配置，是不是可以不用尝试了。

**Comment by irelandKen** [comment]
> 你好，我刚给新配置的主机安装了10.14.5，想使用你的配置文件给OptiPlex 7040 i7安装10.14.5，我看到有个Know issue说只有一个DP口生效，但是我现在使用了两个DP口转接VGA的双显配置，是不是可以不用尝试了。

也可以帮我验证一下是不真的只有一个DP口有效... 之前的这个结论很可能是因为没使用whatevergreen导致的, 现在最新版本使用了whatevergreen, 所以显卡输出效果还有待老哥您来验证哇..(逃

**Comment by docout** [comment]
Is this Clover configuration compatible with 7040 sff? Thanks!

**Comment by irelandKen** [comment]
> Is this Clover configuration compatible with 7040 sff? Thanks!

Not tested, just try it!

**Comment by irelandKen** [comment]
EFI updated for 10.14.5 with IGPU related issue
Thanks for monaive.

**Comment by Beipy** [comment]
Just tested your 7040 file can not run on the 7050 computer, can not recognize the graphics card.
E-mail:beipy0@163.com

**Comment by irelandKen** [comment]
> Just tested your 7040 file can not run on the 7050 computer, can not recognize the graphics card.
> E-mail:[beipy0@163.com](mailto:beipy0@163.com)

replace "config.plist" with the file below, and try it again. 
[config_7050.plist.zip](https://github.com/irelandKen/OptiPlex-7040-Clover-EFI/files/3304294/config_7050.plist.zip)

**Comment by midnightstratos** [comment]
Tested on a 7040 Micro running an i5 6500t. Was able to get it working with a few changes including enabling DellSMBios. HD 530 shows as 1536MB. Can include more details on the changes if needed. Will be testing it further for any issues. Thanks for the files!

**Comment by irelandKen** [comment]
> Tested on a 7040 Micro running an i5 6500t. Was able to get it working with a few changes including enabling DellSMBios. HD 530 shows as 1536MB. Can include more details on the changes if needed. Will be testing it further for any issues. Thanks for the files!

Great~

Yeah, more details is welcome,  you can post you change here~

**Comment by midnightstratos** [comment]
[EFI.zip](https://github.com/irelandKen/Dell-OptiPlex-7040-Clover-EFI/files/3308288/EFI.zip)
This is the EFI folder. Only changes was applying DellSMSBios and adding drivers64UEFI .efi from the UniBeast installer. Applied DVMT fix and installed. 
![64723807_610864216068944_658018723805790208_n](https://user-images.githubusercontent.com/51992480/59809867-791b1800-92b7-11e9-8ab5-e17fb125002e.jpg)

**Comment by Beipy** [comment]
> > Just tested your 7040 file can not run on the 7050 computer, can not recognize the graphics card.
> > E-mail:[beipy0@163.com](mailto:beipy0@163.com)
> 
> replace "config.plist" with the file below, and try it again.
> [config_7050.plist.zip](https://github.com/irelandKen/OptiPlex-7040-Clover-EFI/files/3304294/config_7050.plist.zip)

不知道什么原因还是无法使用。可以加QQ聊吗：

**Comment by cstamper6** [comment]
> Tested on a 7040 Micro running an i5 6500t. Was able to get it working with a few changes including enabling DellSMBios. HD 530 shows as 1536MB. Can include more details on the changes if needed. Will be testing it further for any issues. Thanks for the files!

Trying to get it working on my own 7040m. Can I get some more details on what you did?

**Comment by midnightstratos** [comment]
> Can I get some more details on what you did?

Sure, what details would you like to know? Also - is there a specific step you're stuck on?

**Comment by cstamper6** [comment]
> > Can I get some more details on what you did?
> 
> is there a specific step you're stuck on?
Clover is not showing my Mojave install to boot from.

**Comment by midnightstratos** [comment]
> Clover is not showing my Mojave install to boot from.

Make sure you patch it using DellSMBiosPatch. Its under Kext and Kext Patches in Clover Configurator.

**Comment by wenjiahui** [comment]
> > 你好，我的也是OptiPlex 7040 i7处理器，我现在要装个黑苹果10.14.4，之前是按照https://blog.csdn.net/qq_24671941/article/details/82901391 这篇文章实验的，可惜卡在了安装系统-按F12一直没有出现我的U盘，现在找到了这里，想请教大神指定一下，我是个小白，qq: 2544627835 ,非常期待你的到来，万分感谢~
> 
> Hi, 安装步骤请参考"https://blog.daliansky.net/MacOS-installation-tutorial-XiaoMi-Pro-installation-process-records.html", 安装U盘制作完成后用本EFI替换即可.

你好，请问是用原版镜像制作U盘吗？ 我用了黑果小兵的镜像，替换后没有显示安装选项。

**Comment by irelandKen** [comment]
> > > 你好，我的也是OptiPlex 7040 i7处理器，我现在要装个黑苹果10.14.4，之前是按照https://blog.csdn.net/qq_24671941/article/details/82901391 这篇文章实验的，可惜卡在了安装系统-按F12一直没有出现我的U盘，现在找到了这里，想请教大神指定一下，我是个小白，qq: 2544627835 ,非常期待你的到来，万分感谢~
> > 
> > 
> > Hi, 安装步骤请参考"https://blog.daliansky.net/MacOS-installation-tutorial-XiaoMi-Pro-installation-process-records.html", 安装U盘制作完成后用本EFI替换即可.
> 
> 你好，请问是用原版镜像制作U盘吗？ 我用了黑果小兵的镜像，替换后没有显示安装选项。

Hi, 进入Clover后按F3, 就会看到安装选项, 试试看

**Comment by ONEokDAMON** [comment]
> > > Can I get some more details on what you did?
> > 
> > 
> > is there a specific step you're stuck on?
> 
> Clover is not showing my Mojave install to boot from.

Same issue, not booting install disk, can't figure out which part is wrong

**Comment by wenjiahui** [comment]
> > > > 你好，我的也是OptiPlex 7040 i7处理器，我现在要装个黑苹果10.14.4，之前是按照https://blog.csdn.net/qq_24671941/article/details/82901391 这篇文章实验的，可惜卡在了安装系统-按F12一直没有出现我的U盘，现在找到了这里，想请教大神指定一下，我是个小白，qq: 2544627835 ,非常期待你的到来，万分感谢~
> > > 
> > > 
> > > Hi, 安装步骤请参考"https://blog.daliansky.net/MacOS-installation-tutorial-XiaoMi-Pro-installation-process-records.html", 安装U盘制作完成后用本EFI替换即可.
> > 
> > 
> > 你好，请问是用原版镜像制作U盘吗？ 我用了黑果小兵的镜像，替换后没有显示安装选项。
> 
> Hi, 进入Clover后按F3, 就会看到安装选项, 试试看

你好，按F3没有安装选项。  如果用黑果小兵的镜像，不替换EFI则有安装选项，但是安装后出现 AgraphicsDevicePolicy, loadrf Kexts none. 因为是新手，折腾了好几天都不行，麻烦大佬赐教一下。

**Comment by irelandKen** [comment]
> > > > > 你好，我的也是OptiPlex 7040 i7处理器，我现在要装个黑苹果10.14.4，之前是按照https://blog.csdn.net/qq_24671941/article/details/82901391 这篇文章实验的，可惜卡在了安装系统-按F12一直没有出现我的U盘，现在找到了这里，想请教大神指定一下，我是个小白，qq: 2544627835 ,非常期待你的到来，万分感谢~
> > > > 
> > > > 
> > > > Hi, 安装步骤请参考"https://blog.daliansky.net/MacOS-installation-tutorial-XiaoMi-Pro-installation-process-records.html", 安装U盘制作完成后用本EFI替换即可.
> > > 
> > > 
> > > 你好，请问是用原版镜像制作U盘吗？ 我用了黑果小兵的镜像，替换后没有显示安装选项。
> > 
> > 
> > Hi, 进入Clover后按F3, 就会看到安装选项, 试试看
> 
> 你好，按F3没有安装选项。 如果用黑果小兵的镜像，不替换EFI则有安装选项，但是安装后出现 AgraphicsDevicePolicy, loadrf Kexts none. 因为是新手，折腾了好几天都不行，麻烦大佬赐教一下。

你可以试试先用7040的EFI的UEFI SHELL先修正DVMT显存大小, 然后再黑果小兵的EFI来安装, 安装好后再切回这个EFI试试.

**Comment by irelandKen** [comment]
> > > > > 你好，我的也是OptiPlex 7040 i7处理器，我现在要装个黑苹果10.14.4，之前是按照https://blog.csdn.net/qq_24671941/article/details/82901391 这篇文章实验的，可惜卡在了安装系统-按F12一直没有出现我的U盘，现在找到了这里，想请教大神指定一下，我是个小白，qq: 2544627835 ,非常期待你的到来，万分感谢~
> > > > 
> > > > 
> > > > Hi, 安装步骤请参考"https://blog.daliansky.net/MacOS-installation-tutorial-XiaoMi-Pro-installation-process-records.html", 安装U盘制作完成后用本EFI替换即可.
> > > 
> > > 
> > > 你好，请问是用原版镜像制作U盘吗？ 我用了黑果小兵的镜像，替换后没有显示安装选项。
> > 
> > 
> > Hi, 进入Clover后按F3, 就会看到安装选项, 试试看
> 
> 你好，按F3没有安装选项。 如果用黑果小兵的镜像，不替换EFI则有安装选项，但是安装后出现 AgraphicsDevicePolicy, loadrf Kexts none. 因为是新手，折腾了好几天都不行，麻烦大佬赐教一下。

启动后没有install选项已修复~

**Comment by irelandKen** [comment]
> > > > Can I get some more details on what you did?
> > > 
> > > 
> > > is there a specific step you're stuck on?
> > 
> > 
> > Clover is not showing my Mojave install to boot from.
> 
> Same issue, not booting install disk, can't figure out which part is wrong

启动后没有install选项的问题已修复~
