### ISSUE TITLE
卡在了 usbmsc identifier (non-unique) 这里，出现了禁止符号 ⛔️

### ISSUE THREAD

**Issue by MaYunFei** [optiplex-osx/Dell-OptiPlex-7040-Clover-EFI#8]
直接使用 EFI 卡在了 usbmsc identifier (non-unique) 这里，出现了禁止符号 ⛔️

**Comment by irelandKen** [comment]
USB问题, 可以试试更新一个BIOS设置看看

**Comment by MaYunFei** [comment]
谢谢，最终用小兵的 EFI 和 你这个合了一个，不卡了，应该是 clover config 的问题，具体我也不清楚，不过现在好了，😀️，运行两天也没什么问题
