### ISSUE TITLE
Dell 7040 BIOS Config IFR.txt

### ISSUE THREAD

**Issue by wenjiahui** [optiplex-osx/Dell-OptiPlex-7040-Clover-EFI#9]
你好，请问Dell 7040 BIOS Config IFR.txt这个文件有什么用？

**Comment by irelandKen** [comment]
It's a `UEFI BIOS module` of Dell 7040, which dump by `AMI Flasher utility`

And We can find all BIOS option from this file, include the option that hidden from BIOS Menu.
